//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicekciProje4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int Sip_id { get; set; }
        public string SipAdres { get; set; }
        public int Adet { get; set; }
        public int Tutar { get; set; }
        public int mus_id { get; set; }
        public int Urun_id { get; set; }
    }
}
